name: ci
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file
      - name: Install dependencies
        run: |
          pip install --require-hashes -r requirements.txt -r dev-requirements.txt
      - name: Test with pytest
        run: |
          make test
