name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get python version
        run: |
          python_version=$(cat .python-version)
          echo "python_version=${python_version}" >> $GITHUB_ENV
      - name: Set up Python $
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Install dependencies
        run: |
          pip install --require-hashes -r requirements.txt -r dev-requirements.txt
      - name: Test with pytest
        run: |
          make test
