name: va-web-bot deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 9 * * 0' # Every Sunday at 9:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
